services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    #gpu: all

  server:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - .:/src
    working_dir: /src
    command: tail -f /dev/null
    restart: always

volumes:
  ollama:
